baseURL      = "https://markelca.com/"
title        = "Markel Cuesta"
languageCode = "en-us"
theme        = "hello-friend-ng"
pagination.pagerSize = 10

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "The home of Markel Cuesta — thoughts on software engineering, AI, and the tech industry."

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true

  enableThemeToggle = true

  # Show a global language switcher in the navigation bar
  enableGlobalLanguageMenu = false

  # Metadata mostly used in document's head
  description = "Markel Cuesta’s homepage and blog — software engineering, automation, and tech notes."
  keywords = "Markel Cuesta, markelca, software engineering, backend, automation, programming, tech, blog"
  images = ["https://markelca.com/img/og-default.png"]

  [params.Author]
    name = "Markel Cuesta"

  [params.footer]
    trademark = "2025"
    # author = true
    rss = true
    topText = [
      "<a href=\"https://creativecommons.org/licenses/by-nc/4.0/\" rel=\"license\">CC BY-NC 4.0</a>"
    ]
    bottomText = [
      "Powered by <a href=\"https://gohugo.io/\">Hugo</a>",
      "Made with ♥ by <a href=\"https://github.com/markelca\">Markel Cuesta</a>"
    ]

  [[params.social]]
    name = "github"
    url = "https://github.com/markelca"

  [[params.social]]
    name = "linkedin"
    url = "https://linkedin.com/in/markel-cuesta"

  [[params.social]]
    name = "email"
    url = "mailto:cuesta.markel@proton.me"

  [[params.social]]
    name = "leetcode"
    url = "https://leetcode.com/u/markelca/"

  [[params.social]]
    name = "resume"
    url = "https:/example.com"

[taxonomies]
  category = "blog"
  tag      = "tags"
  series   = "series"

[languages]
  [languages.en]
    title = "MarkelCA.com"
    keywords = "software engineering, backend, automation, tech, blog"
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "markelca.com"
      logoHomeLink = "/"

[[menu.main]]
  identifier = "about"
  name       = "About"
  url        = "/about/"

[[menu.main]]
  identifier = "blog"
  name       = "Blog"
  url        = "/posts/"

[caches]
  [caches.images]
    dir = ':cacheDir/images'
