# baseURL = 'https://example.org/'
# languageCode = 'en-us'
# title = 'My New Hugo Site'

baseurl      = "localhost"
title        = "My Blog"
languageCode = "en-us"
theme        = "hello-friend-ng"
pagination.pagerSize     = 10

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "The home of Markel Cuesta - Software Engineering, Automation, Tech Nerd."

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true

  enableThemeToggle = true
  
  # Show a global language switcher in the navigation bar
  enableGlobalLanguageMenu = false

  # Metadata mostly used in document's head
  description = "My new homepage or blog"
  keywords = "homepage, blog"
  images = [""]
  [params.Author]
    name = "Markel"

  [params.footer]
    trademark = "2025"
    # author = true
    rss = true
    topText = [
      "<a href=\"https://creativecommons.org/licenses/by-nc/4.0/\" rel=\"license\">CC BY-NC 4.0</a>"
    ]
    bottomText = [
      "Powered by <a href=\"https://gohugo.io/\">Hugo</a>",
      "Made with â™¥ by <a href=\"https://github.com/markelca\">Markel Cuesta</a>"
    ]

  [[params.social]]
    name = "github"
    url = "https://github.com/markelca"
  [[params.social]]
    name = "linkedin"
    url = "https://linkedin.com/in/markel-cuesta"
  [[params.social]]
    name = "email"
    url = "mailto:cuesta.markel@proton.me"

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "Markelca.com"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "markelca.com"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/about"

  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/posts"

